ALTER TABLE "SaleItem"
ADD COLUMN "productName" TEXT NOT NULL DEFAULT '';

ALTER TABLE "SaleItem"
ADD COLUMN "costPrice" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "SaleItem"
ADD COLUMN "profit" INTEGER NOT NULL DEFAULT 0;
